global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using SourceGeneratorQuery;
global using Microsoft.CodeAnalysis;
global using RoslynTest.Buildalyzer;
